routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages

Route::group(['middleware' => ['backend-view']], function () {

    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload')->name('unisharp.lfm.upload');
    Route::group(['prefix' => 'laravel-filemanager','as'=>'filemanager'], function () {

        \UniSharp\LaravelFilemanager\Lfm::routes();

    });

});


Route::get('/{lang}', function ($lang){
    App\Langs\Lang::set($lang);
    return redirect()->back();
})->where(['lang'=>'ru|en']);

Route::get('lang/{lang}', 'LanguageController');



/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['backend-view']], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__ . '/frontend/');
});

app/Models/Faq/Faq.php
<?php
/**
 * @author Jakhar <https://github.com/jakharbek>
 * @author Nazrullo <https://github.com/nazrullo>
 * @author O`tkir    <https://github.com/utkir24>
 * @team Adigitalteam <https://github.com/adigitalteam>
 * @package Boxforward
 */

namespace App\Models\Faq;

use App\Langs\LangScope;
use App\Langs\LangScopeTrait;
use App\Models\Category\Category;
use App\Models\Faq\Traits\Attribute\FaqAttribute;
use App\Models\Faq\Traits\Method\FaqMethod;
use App\Models\Faq\Traits\Scope\FaqGlobalScope;
use App\Models\Faq\Traits\Scope\FaqScope;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

/**
 * Class Faq
 * @package App\Models\Faq
 * @method active
 */
class Faq extends Model
{
    const STATUS_ACTIVE = 1;
    const STATUC_DEACTIVE = 0;

    use LangScopeTrait,
        HasSlug,
        FaqAttribute,
        FaqMethod,
        FaqScope;

    /**
     * @var string
     */
    protected $table = 'pages';

    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    public $fillable=[
      'title',
      'description',
      'content',
      'status',
      'sort',
      'lang',
      'lang_hash',
       'slug'
    ];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new FaqGlobalScope());
    }

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->usingLanguage('en')
            ->doNotGenerateSlugsOnUpdate();
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class,'faq_category','faq_id','category_id');
    }


}

app/Models/Faq/Traits/Attribute/FaqAttribute.php
<?php
/**
 * @author Jakhar <https://github.com/jakharbek>
 * @author Nazrullo <https://github.com/nazrullo>
 * @author O`tkir    <https://github.com/utkir24>
 * @team Adigitalteam <https://github.com/adigitalteam>
 * @package Boxforward
 */

namespace App\Models\Faq\Traits\Attribute;


/**
 * Trait UserAttribute.
 */
trait FaqAttribute
{

    /**
     * @return string
     */
    public function getStatusLabelAttribute()
    {
        if ($this->isActive()) {
            return "<span class='badge badge-success'>".__('labels.general.active').'</span>';
        }

        return "<span class='badge badge-danger'>".__('labels.general.inactive').'</span>';
    }

    public function getCategoryIdAttribute()
    {
        $category = $this->categories()->get();
        if($category){
            return $category[0]->id;
        }
       return 0;
    }

    public function getCategoryParentIdAttribute()
    {
        $category = $this->categories()->get();
        if($category){
            return $category[0]->parent_id;
        }
        return 0;
    }




    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        return '<a href="'.route('frontend.faq.index').'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.faq.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit text-dark"></i></a>';
    }


    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {

        return '<a href="' . route('admin.faq.destroy', $this) . '"
                      data-method="delete"
                      data-trans-button-cancel="' . __('buttons.general.cancel') . '"
                      data-trans-button-confirm="' . __('buttons.general.crud.delete') . '"
                      data-trans-title="' . __('strings.backend.general.are_you_sure') . '"
                      class="btn btn-danger">
                      <i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="' . __('buttons.general.crud.delete') . '">
                      </i>
			      </a> ';

    }



    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="Faq Actions">
		  '.$this->show_button.'
		  '.$this->edit_button.'
		  '.$this->delete_button.'
		</div>';
    }
}

app/Http/Controllers/Backend/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Category;

use App\Http\Requests\Backend\Category\ManageCategoryRequest;
use App\Http\Requests\Backend\Category\UpdateCategoryRequest;
use App\Http\Requests\Backend\Page\StoreCategoryRequest;
use App\Langs\Lang;
use App\Models\Category\Category;
use App\Repositories\Backend\Category\CategoryRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    protected $repository;

    /**
     * CategoryController constructor.
     * @param CategoryRepository $repository
     */
    public function __construct(CategoryRepository $repository)
    {
        $this->repository = $repository;

        $this->middleware('permission:read');

        $this->middleware('permission:create', ['only' => ['create','store']]);

        $this->middleware('permission:update', ['only' => ['edit','update']]);

        $this->middleware('permission:delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $nested = Category::nested()->get();
        return view('backend.category.index',['nested'=> $nested,'type'=>0]);
    }

    public function type($type = Category::TYPE_PAGE){

        $nested = Category::nested()->where('type',$type)->get();
        return view('backend.category.index',['nested'=> $nested,'type'=>$type]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    /**
     * @param StorePageRequest $request
     * @return mixed
     */
    public function store(StoreCategoryRequest $request)
    {

        $this->repository->create($request->only(
            'title',
            'description',
            'status',
            'type',
            'slug'
        ));

        return redirect()->route('admin.category.index')->withFlashSuccess(__('Created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ManageCategoryRequest $request, Category $category)
    {

        return view('backend.category.edit')->with(['category'=>$category,'type'=>$category->type]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $this->repository->update($category, $request->all());
        $this->repository->setTranslation($category,$request->only(['translate']));
        return redirect()->route('admin.category.index')->withFlashSuccess(__('alerts.backend.category.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->deleteById($id);
        return redirect()->route('admin.category.index')->withFlashSuccess(__('alerts.backend.category.deleted'));
    }

    public function ajax(Request $request){
        $list = $request->get('list');
        dump($list);
        if(count($list) == 0){return;}
        $list = $this->filterCategoryAjax($list);
        dump($list);
        foreach ($list as $index=>$item){
            $category = Category::find($item['id']);
            $category->parent_id = null;
            $category->sort = $index + 1;
            $category->save();
            if(!array_key_exists('children',$item)){continue;}
            dump("has children");
            $this->updateajaxchild($item);
        }
    }

    private function filterCategoryAjax($list)
    {
        $arr = [];
        foreach ($list as $l) {
            if ($l['id'] == 0 && array_key_exists('children', $l)) {
                $arr += $l['children'];
            } else {
                $arr += $l;
            }
        }

        return $arr;
    }
    private function updateajaxchild($item = []){
        if(!array_key_exists('children',$item)){return false;}
        $childs = $item['children'];
        dump($item);
        foreach ($childs as $index=>$child){
            $category_item = Category::find($item['id']);
            if($category_item){
                $child_category = Category::find($child['id']);
                if($child_category){
                    $child_category->parent_id = $category_item->id;
                    $child_category->sort = $index + 1;
                    $child_category->save();
                }

            }
            $this->updateajaxchild($child);
        }
        return true;
    }

    public function forbiddenResponse()
    {
        return response()->view('backend.includes.errors.errors.403');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/Faq/FaqController.php
<?php
/**
 * @author Jakhar <https://github.com/jakharbek>
 * @author Nazrullo <https://github.com/nazrullo>
 * @author O`tkir    <https://github.com/utkir24>
 * @team Adigitalteam <https://github.com/adigitalteam>
 * @package Boxforward
 */

namespace App\Http\Controllers\Backend\Faq;

use App\Http\Requests\Backend\Faq\ManageFaqRequest;
use App\Http\Requests\Backend\Faq\StoreFaqRequest;
use App\Http\Requests\Backend\Faq\UpdateFaqRequest;
use App\Models\Faq\Faq;
use App\Models\Page\Page;
use App\Models\Page\PageCategories;
use App\Repositories\Backend\Faq\FaqRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class FaqController
 * @package App\Http\Controllers\Backend\Faq
 */
class FaqController extends Controller
{

    /**
     * @var FaqRepository
     */
    protected $faqRepository;


    /**
     * FaqController constructor.
     * @param FaqRepository $faqRepository
     */
    public function __construct(FaqRepository $faqRepository)
    {
        $this->faqRepository = $faqRepository;

        $this->middleware('permission:read');

        $this->middleware('permission:create', ['only' => ['create','store']]);

        $this->middleware('permission:update', ['only' => ['edit','update']]);

        $this->middleware('permission:delete', ['only' => ['destroy']]);
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {

        $search_query = $request->search;

        if(!empty($search_query)){
            $pages = $this->faqRepository->getSearch(25,'created_at','desc',$search_query);
        }
        else{
            $pages = $this->faqRepository->getActivePaginated();
        }
        return view('backend.faq.index',['faqs'=>$pages]);
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backend.faq.create');
    }


    /**
     * @param StoreFaqRequest $request
     * @return mixed
     */
    public function store(StoreFaqRequest $request)
    {
        $this->faqRepository->create($request->only(
            'title',
            'description',
            'content',
            'status',
            'sort',
            'lang',
            'lang_hash'
        ));

        return redirect()->route('admin.faq.index')->withFlashSuccess(__('Created'));
    }


    /**
     * @param ManageFaqRequest $request
     * @param Faq $faq
     * @return mixed
     */
    public function show(ManageFaqRequest $request , Faq $faq )
    {
        return view('backend.faq.show')->withFaq($faq);
    }

    /**
     * @param ManageFaqRequest $request
     * @param Faq $faq
     * @return mixed
     */
    public function edit(ManageFaqRequest $request, Faq $faq)
    {
        return view('backend.faq.edit')->withFaq($faq);
    }

    /**
     * @param UpdateFaqRequest $request
     * @param Faq $faq
     * @return mixed
     */
    public function update(UpdateFaqRequest $request, Faq $faq)
    {

        $this->faqRepository->update($faq, $request->only(
            'title',
            'description',
            'content',
            'status',
            'sort'
        ));

        return redirect()->route('admin.faq.index')->withFlashSuccess(__('alerts.faq.updated'));
    }

    /**
     * @param ManageFaqRequest $request
     * @param Faq $faq
     * @return mixed
     * @throws \Exception
     */
    public function destroy(ManageFaqRequest $request, Faq $faq)
    {
        $this->faqRepository->deleteById($faq->id);
        return redirect()->route('admin.faq.index')->withFlashSuccess(__('alerts.backend.users.deleted'));
    }


}

app/Http/Controllers/Backend/LanguageController.php
<?php
/**
 * @author Jakhar <https://github.com/jakharbek>
 * @author Nazrullo <https://github.com/nazrullo>
 * @author O`tkir    <https://github.com/utkir24>
 * @team Adigitalteam <https://github.com/adigitalteam>
 * @package Boxforward
 */

namespace App\Http\Controllers\Backend;

use App\Langs\Lang;
use App\Http\Controllers\Controller;

/**
 * Class LanguageController.
 */
class LanguageController extends Controller
{
    /**
     * @param $locale
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function __invoke($locale)
    {
        if (array_key_exists($locale, config('locale.languages'))) {
            request()->session()->put('locale_old', Lang::current());
            session()->put('locale', $locale);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/Frontend/Faq/FaqController.php
<?php
/**
 * @author Jakhar <https://github.com/jakharbek>
 * @author Nazrullo <https://github.com/nazrullo>
 * @author O`tkir    <https://github.com/utkir24>
 * @team Adigitalteam <https://github.com/adigitalteam>
 * @package Boxforward
 */

namespace App\Http\Controllers\Frontend\Faq;

use App\Http\Controllers\Controller;
use App\Models\Category\Category;
use App\Repositories\Frontend\Page\PageRepository;

class FaqController extends Controller
{

    protected $faqRepository;


    public function __construct(PageRepository $faqRepository)
    {
        $this->faqRepository = $faqRepository;
    }

    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::langWithTypeAndSort(Category::TYPE_FAQ)->nested()->get();

        return view('frontend.faq.test',['faqs'=>$this->faqRepository->getActivePaginated(),'categories'=>$categories]);
    }

}

resources/views/backend/faq/_form.blade.php
<div class="row mt-4 mb-4">
    <div class="col">
        <div class="form-group row">
            {{ html()->label(__('faq.backend.validation.attributes.title'))->class('col-md-2 form-control-label')->for('title') }}

            <div class="col-md-10">
                {{ html()->text('title')
                    ->class('form-control')
                    ->placeholder(__('faq.backend.validation.attributes.title'))
                    ->required()
                    ->autofocus() }}
            </div><!--col-->
        </div><!--form-group-->
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group row">
            {{ html()->label(__('faq.backend.validation.attributes.description'))->class('col-md-2 form-control-label')->for('description') }}

            <div class="col-md-10">
                {{ html()->text('description')
                    ->class('form-control')
                    ->placeholder(__('faq.backend.validation.attributes.description'))
                     }}
            </div><!--col-->
        </div><!--form-group-->

        <div class="form-group row">
            {{ html()->label(__('faq.backend.validation.attributes.content'))->class('col-md-2 form-control-label')->for('content') }}

            <div class="col-md-10">
                {{ html()->textarea('content')
                    ->class('form-control')
                    ->placeholder(__('faq.backend.validation.attributes.content'))
                    }}
            </div><!--col-->
        </div><!--form-group-->
        <div class="form-group row">
            {{ html()->label(__('faq.backend.validation.attributes.status'))->class('col-md-2 form-control-label')->for('status') }}
            <div class="col-md-10">
                <label class="switch switch-3d switch-primary">
                    {{ html()->checkbox('status')->class('switch-input') }}
                    <span class="switch-label"></span>
                    <span class="switch-handle"></span>
                </label>
            </div><!--col-->
        </div><!--form-group-->
        <div class="form-group row">
            {{ html()->label(__('faq.backend.validation.attributes.sort'))->class('col-md-2 form-control-label')->for('sort') }}
            <div class="col-md-10">
                {{ html()->text('sort')
                    ->value(!isset($faq)? \App\Models\Faq\Faq::where('status',\App\Models\Faq\Faq::STATUS_ACTIVE)->lang()->max('sort') + 1:$faq->sort)
                    ->class('form-control')
                    ->placeholder(__('faq.backend.validation.attributes.sort'))
                    ->attribute('maxlength', 11)
                    }}
            </div><!--col-->
        </div><!--form-group-->
    </div><!--col-->
</div><!--row-->

resources/views/backend/faq/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('faq.backend.label.management') . ' | ' . __('faq.backend.label.create'))

@section('breadcrumb-links')
    @include('backend.faq.includes.breadcrumb-links')
@endsection

@section('content')
    {!!  \App\Langs\LangTabWidget::widget(\App\Models\Faq\Faq::class,'faq')  !!}
    {{ html()->form('POST', route('admin.faq.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('faq.backend.label.management') }}
                        <small class="text-muted">{{ __('faq.backend.label.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->
            <hr />
            @include('backend.faq._form')
            {!!  \App\Langs\LangTabWidget::langForm() !!}
            <div id="tree">
                Category
                <ul id="treeData">
                    {{\App\Models\Category\Category::renderFancy(App\Models\Category\Category::TYPE_FAQ)}}
                    {{html()->hidden('categories')->class('cat-fa')}}
                </ul>
            </div>

        </div><!--card-body-->
        <div class="card-footer clearfix">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.faq.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--col-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
    {{ html()->form()->close() }}
@endsection
@section('category-tree-js')
    <script src="{{ asset('box/js/category-tree.js') }}"></script>
@stop

resources/views/backend/faq/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('faq.backend.label.management') . ' | ' . __('faq.backend.label.edit'))

@section('breadcrumb-links')
    @include('backend.faq.includes.breadcrumb-links')
@endsection

@section('content')
    {!!  \App\Langs\LangTabWidget::widget(\App\Models\Faq\Faq::class,'faq',$faq)  !!}
    {{ html()->modelForm($faq, 'PATCH', route('admin.faq.update', $faq->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('faq.backend.label.management') }}
                        <small class="text-muted">{{ __('faq.backend.label.edit') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />
            @include('backend.faq._form',['faq'=>$faq])
            <div id="tree">
                Category
                <ul id="treeData">
                    {{html()->hidden('categories')->class('cat-fa')}}
                    {{\App\Models\Category\Category::renderFancy(App\Models\Category\Category::TYPE_FAQ,array_pluck($faq->categories,'id'))}}
                </ul>
            </div>
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.auth.user.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
    {{ html()->closeModelForm() }}
@endsection
@section('category-tree-js')
    <script src="{{ asset('box/js/category-tree.js') }}"></script>
@stop

resources/views/backend/faq/index.blade.php
@extends ('backend.layouts.app')

@section('breadcrumb-links')
    @include('backend.faq.includes.breadcrumb-links')
@endsection
@section('content')
    @php($search = [
           'title' => '',
           'description' => '',
           'content' => '',
       ])
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="card-title mb-0">
                        {{ __('faq.backend.label.management') }} <small class="text-muted">{{ __('faq.backend.label.active') }}</small>
                    </h4>
                </div><!--col-->
                <div class="col-lg-4">
                    <form method="get">
                        <input class="form-control" name="search[title]" placeholder="{{__('page.backend.search.find')}}"
                               value="{{ $search['title'] }}"/>
                    </form>
                </div>
                <div class="col-sm-4">
                    @include('backend.faq.includes.header-buttons')
                </div><!--col-->
            </div><!--row-->

            <div class="row mt-4">
                <div class="col">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>{{ __('faq.backend.label.table.id') }}</th>
                                <th>{{ __('faq.backend.label.table.title') }}</th>
                                <th>{{ __('faq.backend.label.table.status') }}</th>
                                <th>{{ __('faq.backend.label.table.sort') }}</th>
                                <th>{{ __('faq.backend.label.table.created_at') }}</th>
                                <th>{{ __('faq.backend.label.table.updated_at') }}</th>
                                <th>{{ __('faq.backend.label.table.actions') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($faqs as $faq)
                                <tr>
                                    <td>{{ $faq->id }}</td>
                                    <td>{{ $faq->title}}</td>
                                    <td>{!! $faq->status_label !!}</td>
                                    <td>{{ $faq->sort }}</td>
                                    <td>{{ $faq->created_at ? $faq->created_at->diffForHumans():$faq->created_at }}</td>
                                    <td>{{ $faq->updated_at ? $faq->updated_at->diffForHumans():$faq->updated_at}}</td>
                                    <td>{!! $faq->action_buttons !!}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!--col-->
            </div><!--row-->
            <div class="row">
                <div class="col-7">
                    <div class="float-left">
                        {{$faqs->links()}}
                    </div>
                </div><!--col-->

                <div class="col-5">
                    <div class="float-right">
                    </div>
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->
    </div><!--card-->
@endsection

resources/views/backend/faq/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('faq.backend.label.management') . ' | ' . __('faq.backend.label.view'))

@section('breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('faq.backend.label.management') }}
                    <small class="text-muted">{{ __('faq.backend.label.view') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-expanded="true"><i class="fas fa-user"></i>
                            {{ __('faq.backend.label.overview') }}</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="overview" role="tabpanel" aria-expanded="true">
                        @include('backend.faq.show.tabs.overview')
                    </div><!--tab-->
                </div><!--tab-content-->
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection